apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceinternal.name }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceinternal.type }}
  ports:
    - port: {{ .Values.serviceinternal.port }}
      targetPort: {{ .Values.serviceinternal.targetPort }}
  selector:
    {{- include "deploy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicepublic.name }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.servicepublic.type }}
  ports:
    - port: {{ .Values.servicepublic.port }}
      targetPort: {{ .Values.servicepublic.targetPort }}
      nodePort: {{ .Values.servicepublic.nodePort }}
  selector:
    {{- include "deploy.selectorLabels" . | nindent 4 }}