trigger:
- master
- dev
- uat

pool:
  vmImage: ubuntu-latest

stages:
- stage: continous_integration
  jobs:
  - job: jb_build_application
    displayName: task's nodejs
    steps:
      - task: Npm@1
        name: ts_get_dependencies
        continueOnError: false
        inputs:
          command: 'install'
      - task: Npm@1
        continueOnError: false
        name: ts_build_application
        inputs:
          command: 'custom'
          customCommand: 'run build'
      - task: Npm@1
        continueOnError: false
        name: ts_unit_test
        inputs:
          command: 'custom'
          customCommand: 'run test-ci'
      # Prepare Analysis Configuration task

      - task: SonarQubePrepare@4
        inputs:
          SonarQube: 'sonarqube'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'angular-azure-devops'
          cliProjectName: 'angular-azure-devops'
          cliSources: '.'
          extraProperties: |
            -Dsonar.typescript.lcov.reportPaths=$(Build.SourcesDirectory)/coverage/lcov.info
      # Run Code Analysis task
      - task: SonarQubeAnalyze@4
      # Publish Quality Gate Result task
      - task: SonarQubePublish@4
        inputs:
          pollingTimeoutSec: '300'

- stage: build images
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!