trigger:
- master
- dev
- uat

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: jb_build_application
    displayName: task's nodejs
    steps:
      - task: Npm@1
        name: ts_get_dependencies
        continueOnError: false
        inputs:
          command: 'install'
      - task: Npm@1
        continueOnError: false
        name: ts_build_application
        inputs:
          command: 'custom'
          customCommand: 'run build'
      - task: Npm@1
        continueOnError: false
        name: ts_unit_test
        inputs:
          command: 'custom'
          customCommand: 'run test-ci'
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!