trigger:
- master
- dev
- uat

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: get-dependencies
    displayName: get dependencies
    steps:
      - task: Npm@1
        inputs:
          command: 'install'
  - job: build
    displayName: build
    steps:
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run build'
  - job: unit-test
    displayName: unit test
    steps:
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run test-ci'
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!