trigger:
- master
- dev
- uat

pool:
  vmImage: ubuntu-latest

stages:
- stage: Dependencies
  jobs:
  - job: getDependencies
    steps:
    - script: echo ================get dependencies================
    - script: echo get dependencies!
    - script: pwd && ls -ls
    - task: Npm@1
      inputs:
        command: 'install'
    - script: pwd && ls -ls
    - script: echo ================ finish get dependencies================
- stage: Build
  jobs:
  - job: Build
    steps:
      - script: echo ================generate build ================
      - script: echo get dependencies!
      - script: pwd && ls -ls
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run build'
      - script: pwd && ls -ls
      - script: echo ================finish generate build ================
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!