---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: devopsappangular
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/haroldo89/devops-app-angular.git

