# definicion de servicio externo.
apiVersion: v1
kind: Service
metadata:
  name: front-external-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32500
  selector:
    app: front-app