# definicion de servicio interno.
apiVersion: v1
kind: Service
metadata:
  name: front-internal-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: front-app