# apiVersion: v1
# kind: Service
# metadata:
#   name: appangular
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 80
#   selector:
#     app: appangular

apiVersion: v1
kind: Service
metadata:
  name: appangular
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30200
  selector:
    app: appangular
